name: Build
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize]
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  XCODE_SCHEME: TextDiffing
jobs:
  build-for-iphone:
    name: Build for iPhone
    runs-on: macos-15
    strategy:
      matrix:
        include:
          - xcode: 16.3
            destination: iPhone 16 Pro
            os: 18.3.1
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          set -o pipefail &&\
          xcodebuild build\
            -scheme ${{ env.XCODE_SCHEME }}\
            -sdk iphonesimulator\
            -destination "platform=iOS Simulator,name=${{ matrix.destination }},OS=${{ matrix.os }}"\
          | xcbeautify --renderer github-actions
  build-for-macos:
    name: Build for macOS
    runs-on: macos-15
    strategy:
      matrix:
        include:
          - xcode: 16.3
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          set -o pipefail &&\
          xcodebuild build\
            -scheme ${{ env.XCODE_SCHEME }}\
            -sdk macosx\
            -destination "platform=macOS"\
          | xcbeautify --renderer github-actions
